### ISSUE TITLE
Update java and spring versions

### ISSUE THREAD

**Issue by kmandalas** [kmandalas/spring-mongodb-graphlookup#4]
Upgrade 

- Java version to: 11
- Spring Boot version to: 2.3.4

These updates may require additional changes, so keep this in mind.

After successful update, check if is reported by GitHub vulnerability has been resolved:

- https://github.com/kmandalas/spring-mongodb-graphlookup/network/alerts

**Comment by jz543fm** [comment]
Hello, can you assing this issue to me

**Comment by kmandalas** [comment]
@jz543fm Hi Juraj. Thanks for offering. Let me know if you need anything.
The goal is to upgrade java to 11 and Spring Boot to 2.3.4 which may bring additional changes to the project though.

**Comment by kmandalas** [comment]
Implemented by @va1m - thank you
